using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Shared.UI.Web
{
	public class CacheConstants
	{
		//declare constants as below

		public const string ApplicationLabelDictionary							    = "ApplicationLabelDictionary";
		public const string ApplicationUserLabelDictionary						    = "ApplicationUserLabelDictionary";
		public const string ApplicationRoleLabelDictionary						    = "ApplicationLabeRolelDictionary";
		public const string ApplicationOperationLabelDictionary					    = "ApplicationOperationLabelDictionary";
		public const string ApplicationEntityFieldLabelLabelDictionary			    = "ApplicationEntityFieldLabelLabelDictionary";
		public const string ApplicationEntityParentalHierarchyLabelDictionary	    = "ApplicationEntityParentalHierarchyLabelDictionary";
		public const string CountryLabelDictionary								    = "CountryLabelDictionary";
		public const string TimeZoneLabelDictionary								    = "TimeZoneLabeRolelDictionary";
		public const string SystemEntityTypeLabelDictionary						    = "SystemEntityTypeLabelDictionary";
		public const string SystemEntityCategoryLabelDictionary					    = "SystemEntityCategoryLabelDictionary";
		public const string UserPreferenceLabelDictionary						    = "UserPreferenceLabeRolelDictionary";
		public const string UserPreferenceKeyLabelDictionary					    = "UserPreferenceKeyLabelDictionary";
		public const string UserPreferenceCategoryLabelDictionary				    = "UserPreferenceCategoryLabelDictionary";
		public const string UserPreferenceDataTypeLabelDictionary				    = "UserPreferenceDataTypeLabelDictionary";
        public const string UserPreferenceSelectedItemLabelDictionary               = "UserPreferenceSelectedItemLabelDictionary";
		public const string TypeOfIssueLabelDictionary							    = "TypeOfIssueLabelDictionary";
		public const string FileTypeLabelDictionary								    = "FileTypeLabelDictionary";
		public const string BatchFileStatusLabelDictionary						    = "BatchFileStatusLabelDictionary";
		public const string BatchFileSetLabelDictionary							    = "BatchFileSetLabelDictionary";
		public const string BatchFileLabelDictionary							    = "BatchFileSetLabelDictionary";
		public const string BatchFileHistoryLabelDictionary						    = "BatchFileHistoryLabelDictionary";
		public const string TaskEntityTypeLabelDictionary						    = "TaskEntityTypeLabelDictionary";
		public const string TaskScheduleTypeLabelDictionary						    = "TaskScheduleTypeLabelDictionary";
		public const string TaskEntityLabelDictionary							    = "TaskEntityLabelDictionary";		
		public const string TaskRunLabelDictionary								    = "TaskRunLabelDictionary";
		public const string ApplicationMonitoredEventLabelDictionary			    = "ApplicationMonitoredEventLabelDictionary";
		public const string ApplicationMonitoredEventEmailLabelDictionary		    = "ApplicationMonitoredEventEmailLabelDictionary";
		public const string ApplicationMonitoredEventProcessingStateLabelDictionary = "ApplicationMonitoredEventProcessingStateLabelDictionary";
		public const string ApplicationMonitoredEventSourceLabelDictionary		    = "ApplicationMonitoredEventSourceLabelDictionary";
		public const string AuditActionLabelDictionary							    = "AuditActionLabelDictionary";
		public const string TaskScheduleLabelDictionary							    = "TaskScheduleLabelDictionary";
        public const string TabParentStructureLabelDictionary                       = "TabParentStructureLabelDictionary";
        public const string TabChildStructureLabelDictionary                        = "TabChildStructureLabelDictionary";
        public const string FunctionalityLabelDictionary                            = "FunctionalityLabelDictionary";
        public const string FunctionalityHistoryLabelDictionary                     = "FunctionalityHistoryLabelDictionary";
        public const string FunctionalityStatusLabelDictionary                      = "FunctionalityStatusLabelDictionary";
        public const string FunctionalityPriorityLabelDictionary                    = "FunctionalityPriorityLabelDictionary";
        public const string FunctionalityEntityStatusLabelDictionary                = "FunctionalityEntityStatusLabelDictionary";
        public const string FunctionalityEntityStatusArchiveLabelDictionary         = "FunctionalityEntityStatusArchiveLabelDictionary";
        public const string HelpPageContextLabelDictionary                          = "HelpPageContextLabelDictionary";
        public const string HelpPageLabelDictionary                                 = "HelpPageLabelDictionary";
        public const string UserLoginStatusLabelDictionary                          = "UserLoginStatusLabelDictionary";
        public const string UserLoginLabelDictionary                                = "UserLoginLabelDictionary";
        public const string LanguageLabelDictionary                                 = "LanguageLabelDictionary";
        public const string ModuleLabelDictionary                                   = "ModuleLabelDictionary";
        public const string DeveloperRoleLabelDictionary                            = "DeveloperRoleLabelDictionary";
        public const string FeatureOwnerStatusLabelDictionary                       = "FeatureOwnerStatusLabelDictionary";
        public const string ModuleOwnerLabelDictionary                              = "ModuleOwnerLabelDictionary";
        public const string EntityOwnerLabelDictionary                              = "EntityOwnerLabelDictionary";
        public const string FunctionalityOwnerLabelDictionary                       = "FunctionalityOwnerLabelDictionary";
        public const string TraceLabelDictionary                                    = "TraceLabelDictionary";
        public const string ApplicationUserProfileImageLabelDictionary              = "ApplicationUserProfileImageLabelDictionary";
        public const string ApplicationUserProfileImageMasterLabelDictionary        = "ApplicationUserProfileImageMasterLabelDictionary";
		public const string ConnectionStringLabelDictionary						    = "ConnectionStringLabelDictionary";
		public const string SubscriberApplicationRoleLabelDictionary                = "SubscriberApplicationRoleLabelDictionary";
		public const string ApplicationRelationLabelDictionary                      = "ApplicationRelationLabelDictionary";

        public const string ApplicationSelectedMode								= "ApplicationSelectedMode";
		public const string ApplicationUserSelectedMode							= "ApplicationUserSelectedMode";
		public const string ApplicationRoleSelectedMode							= "ApplicationLabeRolelDictionary";
		public const string ApplicationOperationSelectedMode					= "ApplicationOperationSelectedMode";
		public const string ApplicationEntityFieldLabelSelectedMode				= "ApplicationEntityFieldLabelSelectedMode";
		public const string ApplicationEntityParentalHierarchySelectedMode		= "ApplicationEntityParentalHierarchySelectedMode";
		public const string CountrySelectedMode									= "CountrySelectedMode";
		public const string TimeZoneSelectedMode								= "TimeZoneLabeRolelSelectedMode";
		public const string SystemEntityTypeSelectedMode						= "SystemEntityTypeSelectedMode";
		public const string SystemEntityCategorySelectedMode					= "SystemEntityCategorySelectedMode";
		public const string UserPreferenceSelectedMode							= "UserPreferenceLabeRolelDictionary";
		public const string UserPreferenceKeySelectedMode						= "UserPreferenceKeySelectedMode";
		public const string UserPreferenceCategorySelectedMode					= "UserPreferenceCategorySelectedMode";
		public const string UserPreferenceDataTypeSelectedMode					= "UserPreferenceDataTypeSelectedMode";
		public const string TypeOfIssueSelectedMode								= "TypeOfIssueSelectedMode";
		public const string FileTypeSelectedMode								= "FileTypeSelectedMode";
		public const string BatchFileStatusSelectedMode							= "BatchFileStatusSelectedMode";
		public const string BatchFileSetSelectedMode							= "BatchFileSetSelectedMode";
		public const string BatchFileSelectedMode								= "BatchFileSetSelectedMode"	;
		public const string BatchFileHistorySelectedMode						= "BatchFileHistorySelectedMode";
		public const string TaskEntityTypeSelectedMode							= "TaskEntityTypeSelectedMode";
		public const string TaskScheduleTypeSelectedMode						= "TaskScheduleTypeSelectedMode";
		public const string TaskEntitySelectedMode								= "TaskEntitySelectedMode";
		public const string TaskRunSelectedMode									= "TaskRunSelectedMode";
		public const string ApplicationMonitoredEventSelectedMode				= "ApplicationMonitoredEventSelectedMode";
		public const string ApplicationMonitoredEventEmailSelectedMode			= "ApplicationMonitoredEventEmailSelectedMode";
		public const string ApplicationMonitoredProcessigStateSelectedMode		= "ApplicationMonitoredProcessigStateSelectedMode";
		public const string ApplicationMonitoredEventSourceSelectedMode			= "ApplicationMonitoredEventSourceSelectedMode";
		public const string AuditActionSelectedMode								= "AuditActionSelectedMode";
		public const string TaskScheduleSelectedMode							= "TaskScheduleSelectedMode";
        public const string MenuCategoryLabelDictionary                         = "MenuCategoryLabelDictionary";
        public const string FieldConfigurationLabelDictionary                   = "FieldConfigurationLabelDictionary";
		public const string FieldConfigurationModeLabelDictionary				= "FieldConfigurationModeLabelDictionary";
		public const string FunctionalityActiveStatusLabelDictionary			= "FunctionalityActiveStatusLabelDictionary";
		public const string FunctionalityXFunctionalityActiveStatusLabelDictionary = "FunctionalityXFunctionalityActiveStatusLabelDictionary";
        public const string FunctionalityImageLabelDictionary                      = "FunctionalityImageLabelDictionary";
		public const string FunctionalityImageAttributeLabelDictionary			   = "FunctionalityImageAttributeLabelDictionary";
		public const string FunctionalityImageInstanceLabelDictionary = "FunctionalityImageInstanceLabelDictionary";
		public const string FunctionalityXFunctionalityImageLabelDictionary		   = "FunctionalityXFunctionalityImageLabelDictionary";
		public const string ReleaseLogStatusLabelDictionary						   = "ReleaseLogStatusLabelDictionary";
		public const string ApplicationRouteLabelDictionary						   = "ApplicationRouteLabelDictionary";
		public const string ApplicationRouteParameterLabelDictionary			   = "ApplicationRouteParameterLabelDictionary";
		public const string UserLoginHistoryLabelDictionary						   = "UserLoginHistoryLabelDictionary";
		public const string DateRangeTitleLabelDictionary						   = "DateRangeTitleLabelDictionary";
		public const string ApplicationModeLabelDictionary						   = "ApplicationModeLabelDictionary";
		public const string ReleaseIssueTypeLabelDictionary						   = "ReleaseIssueTypeLabelDictionary";
		public const string ReleasePublishCategoryLabelDictionary				   = "ReleasePublishCategoryLabelDictionary";
		public const string SearchKeyLabelDictionary							   = "SearchKeyLabelDictionary";
		public const string SearchKeyDetailLabelDictionary						   = "SearchKeyDetailLabelDictionary";
		public const string SearchKeyDetailItemLabelDictionary				       = "SearchKeyDetailItemLabelDictionary";
		public const string FieldConfigurationModeCategoryLabelDictionary		   = "FieldConfigurationModeCategoryLabelDictionary";
		public const string ReleaseLogLabelDictionary							   = "ReleaseLogLabelDictionary";
		public const string ApplicationUserTitleLabelDictionary					   = "ApplicationUserTitleLabelDictionary";
		public const string ReleaseLogDetailLabelDictionary						   = "ReleaseLogDetailLabelDictionary";
        public const string FieldConfigurationModeAccessModeLabelDictionary        = "FieldConfigurationModeAccessModeLabelDictionary";
        public const string FieldConfigurationModeXApplicationRoleLabelDictionary  = "FieldConfigurationModeXApplicationRoleLabelDictionary";
        public const string ThemeLabelDictionary                                   = "ThemeLabelDictionary";
        public const string ThemeKeyLabelDictionary                                = "ThemeKeyLabelDictionary";
        public const string ThemeCategoryLabelDictionary                           = "ThemeCategoryLabelDictionary";
        public const string ThemeDetailLabelDictionary                             = "ThemeDetailsLabelDictionary";
		public const string SystemForeignRelationshipLabelDictionary			   = "SystemForeignRelationshipLabelDictionary";
		public const string AllEntityDetailLabelDictionary						   = "AllEntityDetailLabelDictionary";
		public const string SystemForeignRelationshipTypeLabelDictionary		   = "SystemForeignRelationshipTypeLabelDictionary";
		public const string SystemForeignRelationshipDatabaseLabelDictionary	   = "SystemForeignRelationshipDatabaseLabelDictionary";
		public const string VacationPlanLabelDictionary							   = "VacationPlanLabelDictionary";
        public const string ProjectPortfolioGroupLabelDictionary                   = "ProjectPortfolioGroupLabelDictionary";
        public const string TaskRoleLabelDictionary                                = "TaskRoleLabelDictionary";
        public const string RenumberMigrationLabelDictionary                       = "RenumberMigartionLabelDictionary";
        public const string DatabaseChangeLogLabelDictionary                       = "DatabaseChangeLogLabelDictionary";
		public const string ProjectPortfolioGroupXProjectPortfolioLabelDictionary  = "ProjectPortfolioGroupXProjectPortfolioLabelDictionary";
        public const string DBNameLabelDictionary                                  = "DBNameLabelDictionary";
		public const string DBProjectNameLabelDictionary                            = "DBProjectNameLabelDictionary";
		public const string DBComponentNameLabelDictionary                          = "DBComponentNameLabelDictionary";
		public const string AuditHistoryLabelDictionary								= "AuditHistoryLabelDictionary";
		public const string CustomTimeCategoryLabelDictionary						= "CustomTimeCategoryLabelDictionary";
		public const string EntityLabelDictionary									= "EntityLabelDictionary";
		public const string WorkTicketLabelDictionary                               = "WorkTicketLabelDictionary";
		public const string EntityXWorkTicketLabelDictionary                        = "EntityXWorkTicketLabelDictionary";

		
	}
}