IF EXISTS 
(
	SELECT	*	FROM	dbo.sysindexes
	WHERE	id		= OBJECT_ID(N'[dbo].TransactionEventBuy')
	AND		name	= N'UQ_TransactionEventBuy_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId'
)
BEGIN
	PRINT	'Dropping UQ_TransactionEventBuy_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId'
	ALTER	TABLE dbo.TransactionEventBuy
	DROP	CONSTRAINT	UQ_TransactionEventBuy_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId
END
GO

ALTER TABLE dbo.TransactionEventBuy
ADD CONSTRAINT UQ_TransactionEventBuy_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId UNIQUE NONCLUSTERED
(
	ApplicationId, TransactionTypeId, CustodianId, StrategyId, AccountSpecificTypeId, InvestmentTypeId
)
GO
