IF EXISTS 
(
	SELECT	*	FROM	dbo.sysindexes
	WHERE	id		= OBJECT_ID(N'[dbo].TransactionEventSellShort')
	AND		name	= N'UQ_TransactionEventSellShort_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId'
)
BEGIN
	PRINT	'Dropping UQ_TransactionEventSellShort_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId'
	ALTER	TABLE dbo.TransactionEventSellShort
	DROP	CONSTRAINT	UQ_TransactionEventSellShort_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId
END
GO

ALTER TABLE dbo.TransactionEventSellShort
ADD CONSTRAINT UQ_TransactionEventSellShort_ApplicationId_TransactionTypeId_CustodianId_StrategyId_AccountSpecificTypeId_InvestmentTypeId UNIQUE NONCLUSTERED
(
	ApplicationId, TransactionTypeId, CustodianId, StrategyId, AccountSpecificTypeId, InvestmentTypeId
)
GO
