using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Shared.WebCommon.UI.Web;
using System.Text;
using System.Web.UI.HtmlControls;
using System.Data;
using Framework.UI.Web.BaseClasses;

namespace Shared.UI.Web.Admin
{
	public partial class SessionObjects : Framework.UI.Web.BaseClasses.PageBasePage
    {

        #region Methods

        private void LoadSessionObjects()
        {
            if (Session.Count > 0)
            {
				         
                foreach (var key in Session.Keys)
                {
                    var linkButton = new LinkButton();
                    linkButton.Text = Convert.ToString(key);
                    linkButton.Click += new EventHandler(linkButton_Click);

                    var innerDiv = new HtmlGenericControl("div");
					var divider = new HtmlGenericControl("div");
					var li = new HtmlGenericControl("li");
                    innerDiv.Attributes.CssStyle.Add("height", "20px");
                    innerDiv.Attributes.CssStyle.Add("width", "40px");
					divider.Attributes.CssStyle.Add("height", "5px");
					divider.Attributes.CssStyle.Add("width", "auto");
					divider.Attributes.CssStyle.Add("display", "inline-block");
                	innerDiv.Controls.Add(linkButton);
                    divObjects.Controls.Add(innerDiv);
					divObjects.Controls.Add(divider);
                }
		
                LoadSessionObjectValue(Session.Keys[0]);

				
            }
        }

        private void LoadSessionObjectValue(string sessionKey)
        {
        	divObjects2.InnerText = sessionKey;
            divValue.InnerHtml = String.Empty;
            var sessionValues = Session[sessionKey]; 
            var objType = sessionValues.GetType().Name;
            if (sessionValues is int || sessionValues is string || sessionValues is bool)
            {                
                divValue.InnerText = Convert.ToString(sessionValues);
            }
            else if (sessionValues is DataTable || sessionValues is List<ApplicationUserRole> || sessionValues is List<UPreference>)
            {
                var gv = new GridView();
                gv.AutoGenerateColumns = true;
                gv.AutoGenerateDeleteButton = false;
                gv.AutoGenerateEditButton = false;
                gv.AutoGenerateSelectButton = false;
                gv.Style.Add("table-layout", "fixed");
                gv.Width = Unit.Parse("900px");
                gv.DataSource = sessionValues;
                gv.DataBind();
                divValue.Controls.Add(gv);
            }
            else if (sessionValues is DataSet)
            {
                var ds = (DataSet)sessionValues;
                foreach (DataTable dt in ds.Tables)
                {
                    var gv = new GridView();
                    gv.AutoGenerateColumns = true;
                    gv.AutoGenerateDeleteButton = false;
                    gv.AutoGenerateEditButton = false;
                    gv.AutoGenerateSelectButton = false;
                    gv.Style.Add("table-layout", "fixed");
                    gv.Width = Unit.Parse("900px");
                    gv.DataSource = dt;
                    gv.DataBind();
                    divValue.Controls.Add(gv);
                }
            }
            lblObjectType.Text = objType;
        }

        #endregion

        #region Events

        protected override void OnInit(EventArgs e)
        {
            LoadSessionObjects();

			SettingCategory = "SessionObjectsDefaultView";
			BreadCrumbObject = Master.BreadCrumbObject;
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {

            }
        }

        void linkButton_Click(object sender, EventArgs e)
        {
            var btn = (LinkButton)sender;
            var sessionKey = btn.Text;
            LoadSessionObjectValue(sessionKey);
        }

        #endregion

    }
}