using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ApplicationContainer.UI.Web.CommonCode
{
	public class CacheConstants
	{		
		public const string QuestionLabelDictionary									= "QuestionLabelDictionary";
        public const string ReportLabelDictionary                                   = "ReportLabelDictionary";
        public const string ReportCategoryLabelDictionary                           = "ReportCategoryLabelDictionary";
		public const string ClientLabelDictionary									= "ClientLabeRolelDictionary";
		public const string ProjectLabelDictionary									= "ProjectLabelDictionary";
		public const string LayerLabelDictionary									= "LayerLabelDictionary";
		public const string ActivityStateLabelDictionary							= "ActivityStateLabelDictionary";
		public const string RiskLabelDictionary										= "RiskLabeRolelDictionary";
		public const string RewardLabelDictionary									= "RewardLabelDictionary";
		public const string SkillLabelDictionary									= "SkillLabelDictionary";
		public const string SkillLevelLabelDictionary								= "SkillLevelLabelDictionary";
		public const string MilestoneLabelDictionary								= "MilestoneLabelDictionary";
		public const string NeedLabelDictionary										= "NeedLabeRolelDictionary";
		public const string FeatureLabelDictionary									= "FeatureLabelDictionary";
		public const string TaskTypeLabelDictionary									= "TaskTypeLabelDictionary";
		public const string TaskPackageLabelDictionary								= "TaskPackageLabelDictionary";
		public const string TaskPriorityTypeLabelDictionary							= "TaskPriorityTypeLabeRolelDictionary";
		public const string TaskLabelDictionary										= "TaskLabelDictionary";
		public const string TaskFormulationLabelDictionary							= "TaskFormulationLabelDictionary";
		public const string TaskPriorityXApplicationUserLabelDictionary				= "TaskPriorityXApplicationUserLabelDictionary";
		public const string TaskRiskRewardRankingXPersonLabelDictionary				= "TaskRiskRewardRankingXPersonLabelDictionary";
		public const string ActivityLabelDictionary									= "ActivityLabelDictionary";
		public const string ActivityAlgorithmLabelDictionary						= "ActivityAlgorithmLabelDictionary";
		public const string TaskAlgorithmLabelDictionary							= "TaskAlgorithmLabelDictionary";		
		public const string TaskAlgorithmItemLabelDictionary						= "TaskAlgorithmItemLabelDictionary";		
		public const string ProjectTimeLineLabelDictionary							= "ProjectTimeLineLabelDictionary";
		public const string ScheduleLabelDictionary									= "ScheduleLabelDictionary";
		public const string ScheduleQuestionLabelDictionary							= "ScheduleQuestionLabelDictionary";
		public const string ScheduleItemLabelDictionary								= "ScheduleItemLabelDictionary";
		public const string FileTypeLabelDictionary									= "FileTypeLabelDictionary";
		public const string TaskEntityTypeLabelDictionary							= "TaskEntityTypeLabelDictionary";			
		public const string TaskEntityLabelDictionary								= "TaskEntityLabelDictionary";		
		public const string TaskRunLabelDictionary									= "TaskRunLabelDictionary";				
		public const string FeatureGroupLabelDictionary								= "FeatureGroupLabelDictionary";
		public const string FeatureXFeatureRuleLabelDictionary						= "FeatureXFeatureRuleLabelDictionary";
		public const string QuestionCategoryLabelDictionary							= "QuestionCategoryLabelDictionary";
		public const string FeatureRuleCategoryLabelDictionary						= "FeatureRuleCategoryLabelDictionary";
		public const string TaskStatusTypeLabelDictionary							= "TaskStatusTypeLabelDictionary";
        public const string DeliverableArtifactLabelDictionary						= "DeliverableArtifactLabelDictionary";
        public const string FeatureRuleStatusLabelDictionary						= "FeatureRuleStatusLabelDictionary";
		public const string FeatureRuleLabelDictionary								= "FeatureRuleLabelDictionary";
		public const string TaskNoteLabelDictionary									= "TaskNotesLabelDictionary";
        public const string DeliverableArtifactStatusLabelDictionary				= "DeliverableArtifactStatusLabelDictionary";
		public const string UseCaseLabelDictionary									= "UseCaseLabelDictionary";
		public const string UseCaseActorLabelDictionary								= "UseCaseActorLabelDictionary";
		public const string UseCaseRelationshipLabelDictionary						= "UseCaseRelationshipLabelDictionary";
		public const string UseCaseActorXUseCaseLabelDictionary						= "UseCaseActorXUseCaseLabelDictionary";
		public const string TestSuiteLabelDictionary								= "TestSuiteLabelDictionary";
        public const string TestCaseLabelDictionary									= "TestCaseLabelDictionary";
		public const string UseCaseStepLabelDictionary								= "UseCaseStepLabelDictionary";
		public const string UseCasePackageLabelDictionary							= "UseCasePackageLabelDictionary";
        public const string MilestoneFeatureStateLabelDictionary					= "MilestoneFeatureStateLabelDictionary";
		public const string ProjectXUseCaseStateLabelDictionary						= "ProjectXUseCaseStateLabelDictionary";
		public const string ProjectXUseCaseLabelDictionary							= "ProjectXUseCaseLabelDictionary";
		public const string TestRunLabelDictionary									= "TestRunLabelDictionary";
		public const string ProjectUseCaseStatusLabelDictionary						= "ProjectUseCaseStatusLabelDictionary";
        public const string TaskPackageXOwnerXTaskLabelDictionary					= "TaskPackageXOwnerXTaskDictionary";
        public const string TestCaseOwnerLabelDictionary							= "TestCaseOwnerLabelDictionary";
        public const string TestCasePriorityLabelDictionary							= "TestCasePriorityLabelDictionary";
        public const string TestCaseStatusLabelDictionary							= "TestCaseStatusLabelDictionary";
        public const string TestSuiteXTestCaseArchiveLabelDictionary				= "TestSuiteXTestCaseArchiveLabelDictionary";
		public const string TestSuiteXTestCaseLabelDictionary						= "TestSuiteXTestCaseLabelDictionary";
        public const string NotificationEventTypeLabelDictionary					= "NotificationEventTypeLabelDictionary";
        public const string NotificationRegistrarLabelDictionary					= "NotificationRegistrarLabelDictionary";
        public const string UseCaseWorkFlowCategoryLabelDictionary					= "UseCaseWorkFlowCategoryLabelDictionary";
        public const string MilestoneXFeatureArchiveLabelDictionary					= "MilestoneXFeatureArchiveLabelDictionary";
		public const string MilestoneXFeatureLabelDictionary						= "MilestoneXFeatureLabelDictionary";
        public const string UseCaseXUseCaseStepLabelDictionary						= "UseCaseXUseCaseStepLabelDictionary";
		public const string NotificationPublisherLabelDictionary					= "NotificationPublisherLabelDictionary";
		public const string FunctionalityActiveStatusLabelDictionary				= "FunctionalityActiveStatusLabelDictionary";
        public const string RunTimeFeatureLabelDictionary							= "RunTimeFeatureLabelDictionary";
        public const string ApplicationModeXRunTimeFeatureLabelDictionary			= "ApplicationModeXRunTimeFeatureLabelDictionary";
        public const string ProjectUseCaseStatusArchiveLabelDictionary				= "ProjectUseCaseStatusArchiveLabelDictionary";
		public const string TaskXActivityInstanceLabelDictionary					= "TaskXActivityInstanceLabelDictionary";
        public const string ProductivityAreaLabelDictionary							= "ProductivityAreaLabelDictionary";
        public const string ProductivityAreaFeatureLabelDictionary					= "ProductivityAreaFeatureLabelDictionary";
        public const string ProductivityAreaXProductivityAreaFeatureLabelDictionary = "ProductivityAreaXProductivityAreaFeatureLabelDictionary";
        public const string ProductivityAreaFeatureXApplicationUserLabelDictionary	= "ProductivityAreaFeatureXApplicationUserLabelDictionary";
		public const string NotificationSubscriberLabelDictionary					= "NotificationSubscriberLabelDictionary";
		public const string ActivityXDeliverableArtifactLabelDictionary				= "ActivityXDeliverableArtifactLabelDictionary";
		public const string TaskXDeliverableArtifactLabelDictionary					= "TaskXDeliverableArtifactLabelDictionary";
		public const string CompetencyLabelDictionary								= "CompetencyLabelDictionary";	
		public const string TaskXCompetencyLabelDictionary							= "TaskXCompetencyLabelDictionary";
		public const string CompetencyXSkillLabelDictionary							= "CompetencyXSkillLabelDictionary";
		public const string EntityDateRangeStateTypeLabelDictionary					= "EntityDateRangeStateTypeLabelDictionary";
		public const string EntityDateRangeStateLabelDictionary						= "EntityDateRangeStateLabelDictionary";
		public const string UseCasePackageXUseCaseLabelDictionary					= "UseCasePackageXUseCaseLabelDictionary";
		public const string SkillXPersonXSkillLevelLabelDictionary					= "SkillXPersonXSkillLevelLabelDictionary";
        public const string FunctionalityXFunctionalityImageLabelDictionary         = "FunctionalityXFunctionalityImageLabelDictionary";
        public const string ProjectPortfolioLabelDictionary                         = "ProjectPortfolioLabelDictionary	";
        public const string ProjectPortfolioGroup                                   = "ProjectPortfolioGroup";
		public const string ScheduleDetailLabelDictionary						    = "ScheduleDetailLabelDictionary";
		public const string ScheduleStateLabelDictionary							= "ScheduleStateLabelDictionary";
		public const string ScheduleHistoryLabelDictionary							= "ScheduleHistoryLabelDictionary";
        public const string ReportXReportCategoryLabelDictionary                    = "ReportXReportCategoryLabelDictionary";
		public const string CustomTimeLogLabelDictionary							= "CustomTimeLogLabelDictionary";
		public const string CustomTimeCategoryLabelDictionary						= "CustomTimeCategoryLabelDictionary";
    }
}
