//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationContainer.UI.Web {


	public partial class Sample
	{
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new Framework.UI.Web.BaseClasses.PageDefaultMaster Master {
            get {
                return ((Framework.UI.Web.BaseClasses.PageDefaultMaster)(base.Master));
            }
        }
    }
}
