//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.UI.Web.AuthenticationAndAuthorization.ApplicationUserProfileImageMaster.Controls {
    
    
    public partial class SearchFilter {

		protected global::ApplicationContainer.UI.Web.BaseUI.SearchFilterControl SearchFilterControl;
    }
}
